// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjfYxC7QZUWGprzlxeLPTzhMt2xEJq_SA',
    appId: '1:839123437645:web:3a9ee5841d225d0164f404',
    messagingSenderId: '839123437645',
    projectId: 'chatup-a221d',
    authDomain: 'chatup-a221d.firebaseapp.com',
    storageBucket: 'chatup-a221d.firebasestorage.app',
    measurementId: 'G-X3MDSKX7WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBuJgiC9VWd4QUO0WK-S9theja58wFos',
    appId: '1:839123437645:android:f80c8e8654d92ba264f404',
    messagingSenderId: '839123437645',
    projectId: 'chatup-a221d',
    storageBucket: 'chatup-a221d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD09KbTWtuuc8IHiN14e_7gppWH0cSv7es',
    appId: '1:839123437645:ios:1f4cfad61af09e7d64f404',
    messagingSenderId: '839123437645',
    projectId: 'chatup-a221d',
    storageBucket: 'chatup-a221d.firebasestorage.app',
    iosBundleId: 'com.example.chatup',
  );
}
